name: Generate JWT

on: 
 workflow_dispatch:

jobs:
  generate-jwt:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        pip install JWT
        pip install jwcrypto
        pip install jwt
        run: |
        $ curl -i -X POST \
             -H "Authorization: Bearer ***" \
             -H "Accept: application/vnd.github+json" \
                 https://api.github.com/app/installations/34148902/access_tokens
   
      env:
        PYTHONPATH: /usr/local/lib/python3.8/site-packages
    - name: Generate JWT
      run: |
        python3 my_jwt.py
    
