name: My Workflow

on: 
  push:
  
  workflow_dispatch:

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Make API request
        run: |
          const octokit = new (require('@octokit/rest'))();
          octokit.authenticate({
            type: 'app',
            token: ${{ steps.auth.outputs.token }}
          });
          octokit.users.getAuthenticated({}).then(result => {
            console.log(result.data.login);
          });
