name: Generate JWT

on: 
 workflow_dispatch:

jobs:
  generate-jwt:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        pip install  pyjwt
        pip install jwcrypto
        pip install pyJWT
    - run: |
        curl -i -X POST \
         -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c" \
         -H "Accept: application/vnd.github+json" \
           https://api.github.com/app/installations/292855/access_tokens
      env:
        PYTHONPATH: /usr/local/lib/python3.8/site-packages
    - name: Generate JWT
      run: |
        python3 gen_jwt.py
    
